# Generated by Django 5.1.7 on 2025-06-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0002_alter_packageoffers_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='project_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elite_interior.category'),
        ),
    ]
