# Generated by Django 5.1.7 on 2025-06-26 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0003_blog_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_blogs', to='elite_interior.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='project_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_category_blogs', to='elite_interior.category'),
        ),
    ]
