# Generated by Django 5.1.7 on 2025-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0005_remove_blogcategory_name_blogcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
