# Generated by Django 5.1.7 on 2025-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0008_unit_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
