# Generated by Django 5.1.7 on 2025-08-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0009_product_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
