# Generated by Django 5.1.7 on 2025-08-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0011_product_design_for_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design_for',
        ),
    ]
