# Generated by Django 5.1.7 on 2025-08-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0012_remove_product_design_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
