# Generated by Django 5.1.7 on 2025-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0014_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
