# Generated by Django 5.1.7 on 2025-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0016_product_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='project_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Material Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'material'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Material Category'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Product sub category'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Material Unit'},
        ),
    ]
