# Generated by Django 5.1.7 on 2025-08-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0018_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatwedo_grid',
            options={'verbose_name': 'OUR SERVICE GRID'},
        ),
    ]
