# Generated by Django 5.1.7 on 2025-09-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0019_alter_whatwedo_grid_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='healine',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
