# Generated by Django 5.1.7 on 2025-09-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0020_remove_homeslider_healine_homeslider_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='sub_headline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
