# Generated by Django 5.1.7 on 2025-11-15 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0024_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='accessories/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='elite_interior.category')),
            ],
        ),
    ]
