# Generated by Django 5.1.7 on 2025-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0025_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
