# Generated by Django 5.1.7 on 2025-11-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0027_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
