# Generated by Django 5.2.1 on 2025-11-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0030_seoservicepage_seoserviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOServiceImage',
        ),
        migrations.DeleteModel(
            name='SEOServicePage',
        ),
    ]
