# Generated by Django 5.2.1 on 2025-12-12 13:34

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0032_seoservicepage_seoserviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_link',
            field=models.CharField(help_text='Paste the YouTube video ID only (e.g. FT9g4LLrR5c)', max_length=100, validators=[django.core.validators.RegexValidator(message='Enter only the 11-character YouTube video ID (e.g. FT9g4LLrR5c).', regex=re.compile('^[A-Za-z0-9_-]{11}$'))]),
        ),
    ]
