# Generated by Django 5.2.1 on 2025-12-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0033_alter_youtubevideo_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_link',
            field=models.CharField(help_text='Paste the YouTube video ID only (e.g. FT9g4LLrR5c)', max_length=100),
        ),
    ]
