# Generated by Django 5.2.1 on 2025-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0034_alter_youtubevideo_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageoffers',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL', max_length=500, null=True),
        ),
    ]
