# Generated by Django 5.2.1 on 2025-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0035_packageoffers_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvideo',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='aboutvideo',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Paste YouTube URL or video ID', max_length=500, null=True),
        ),
    ]
