# Generated by Django 5.2.1 on 2026-02-04 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0036_remove_aboutvideo_youtube_id_aboutvideo_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=200)),
                ('GST', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullSemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='quotation_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=100)),
                ('core_material', models.CharField(max_length=100)),
                ('finish_material', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('specification', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elite_interior.client')),
                ('full_semi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elite_interior.fullsemi')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elite_interior.image')),
            ],
        ),
    ]
