# Generated by Django 5.2.1 on 2026-02-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0037_client_fullsemi_image_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='area',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='full_semi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elite_interior.fullsemi'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elite_interior.image'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.FloatField(editable=False),
        ),
    ]
