# Generated by Django 5.2.1 on 2026-02-05 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0038_alter_quotation_area_alter_quotation_full_semi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='estimate_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='estimate_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
