# Generated by Django 5.2.11 on 2026-03-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0039_client_created_at_client_estimate_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='client',
            name='estimate_end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='estimate_start_date',
        ),
        migrations.AddField(
            model_name='client',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_mode',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
