# Generated by Django 5.2.11 on 2026-03-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0041_client_created_at_client_estimate_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Home Den', max_length=200)),
                ('google_site_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=255)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID (G-XXXXXXX)', max_length=50)),
            ],
        ),
    ]
