# Generated by Django 5.2.11 on 2026-03-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0042_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('base_rate', models.FloatField()),
                ('laminate_price', models.FloatField(default=0)),
                ('acrylic_price', models.FloatField(default=0)),
                ('veneer_price', models.FloatField(default=0)),
                ('silver_package', models.FloatField(default=0)),
                ('gold_package', models.FloatField(default=0)),
                ('platinum_package', models.FloatField(default=0)),
            ],
        ),
    ]
