# Generated by Django 5.2.11 on 2026-03-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0043_interiorprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorprice',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
