# Generated by Django 5.2.11 on 2026-03-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0045_aipackage_aiproduct_finish_location_plywood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.FloatField()),
                ('ai_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elite_interior.aipackage')),
                ('ai_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elite_interior.aiproduct')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elite_interior.finish')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elite_interior.location')),
                ('plywood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elite_interior.plywood')),
            ],
        ),
    ]
