# Generated by Django 5.2.11 on 2026-03-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0046_interiorprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finish',
            new_name='AiFinish',
        ),
        migrations.RenameModel(
            old_name='InteriorPrice',
            new_name='AiInteriorPrice',
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='AiLocation',
        ),
        migrations.RenameModel(
            old_name='Plywood',
            new_name='AiPlywood',
        ),
    ]
