# Generated by Django 5.2.11 on 2026-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0048_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
