# Generated by Django 5.2.11 on 2026-05-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0050_messagetemplate_campaignlog_campaignrecipient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='QuotationImage',
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_og/'),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seoservicepage',
            name='schema_type',
            field=models.CharField(default='Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatwedo_grid',
            name='size',
            field=models.CharField(choices=[('large', 'Large'), ('small', 'Small'), ('tall', 'Tall')], max_length=10),
        ),
    ]
