# Generated by Django 5.1.7 on 2026-07-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0051_rename_image_quotationimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('home', 'Complete Home Interior'), ('kitchen', 'Modular Kitchen'), ('wardrobe', 'Wardrobe'), ('tv_unit', 'TV Unit')], max_length=20)),
                ('plan', models.CharField(choices=[('compact', 'Compact'), ('signature', 'Signature'), ('luxury', 'Luxury'), ('royal', 'Royal')], max_length=20)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorPackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='elite_interior.interiorpackage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
