# Generated by Django 5.1.7 on 2026-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0052_interiorpackage_interiorpackagefeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interiorpackage',
            options={'ordering': ['starting_price']},
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='minimum_budget',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='price_per_sqft',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='service',
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='package_brochures/'),
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='name',
            field=models.CharField(choices=[('comfort', 'Comfort'), ('compact', 'Compact'), ('signature', 'Signature'), ('luxury', 'Luxury'), ('royal', 'Royal')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Example: 625000', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='suitable_for',
            field=models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('villa', 'Villa'), ('commercial', 'Commercial')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='warranty_years',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='interiorpackagefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: bi-check-circle', max_length=50),
        ),
    ]
