# Generated by Django 5.2.11 on 2026-07-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0053_alter_interiorpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interiorpackage',
            options={'ordering': ['display_order'], 'verbose_name': 'Interior Package', 'verbose_name_plural': 'Interior Packages'},
        ),
        migrations.RenameField(
            model_name='interiorpackagefeature',
            old_name='feature',
            new_name='title',
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in website and AI'),
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='interiorpackagefeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('estimate', 'Approximate Estimate'), ('site_visit', 'Site Visit'), ('quotation', 'Quotation Request')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='elite_interior.interiorpackage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Contact Form'), ('ai_chat', 'AI Chatbot'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone Call'), ('walkin', 'Walk-in')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interiorpackagefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
