# Generated by Django 5.2.11 on 2026-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0054_alter_interiorpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interiorpackage',
            options={'ordering': ['starting_price']},
        ),
        migrations.RenameField(
            model_name='interiorpackagefeature',
            old_name='title',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='interiorpackagefeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='package',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='interiorpackagefeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: bi-check-circle', max_length=50),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
