# Generated by Django 5.2.11 on 2026-07-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0055_alter_interiorpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interiorpackage',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='interiorpackage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interiorpackage',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='PackageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='elite_interior.interiorpackage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elite_interior.packagesection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.DeleteModel(
            name='InteriorPackageFeature',
        ),
    ]
