# Generated by Django 5.2.11 on 2026-07-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0056_alter_interiorpackage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageOffers',
        ),
    ]
