# Generated by Django 5.2.11 on 2026-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0057_delete_packageoffers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='homeslider',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Upload mobile version (Recommended: 1080 × 1920)', null=True, upload_to='slider_mobile/'),
        ),
    ]
