# Generated by Django 5.1.7 on 2025-06-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_interior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageoffers',
            name='subtitle',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
